name: scheduled_pipeline_ir

on:
  # Allow manual runs from the Actions UI
  workflow_dispatch: {}

  schedule:
    # Runs every Saturday and Sunday at 10:00 UTC. GitHub Actions uses UTC for cron schedules.
    - cron: '0 9 * * *'

jobs:
  incremental-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv (astral-sh)
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies with uv
        run: uv sync

      - name: Ingest data from data.assemblee-nationale.fr
        run: uv run ./ingestion/run.py

      - name: Caching data folder
        uses: actions/cache@v3
        with:
          path: |
            data/
          key: data-cache-${{ hashFiles('data/**') }}
          restore-keys: |
            data-cache-${{ hashFiles('data/**') }}
            data-cache-

      - name: DBT Incremental refresh Motherduck DB
        run: cd ./dbt && uv run dbt run
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          ENV: ${{ vars.ENV }}